services:
  - type: web
    name: github-api-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false  # sẽ cài thủ công
